
name: smithproxy
version: 0.9.31
summary: Fast and featured transparent TCP/UDP/TLS proxy
description: |
  Smithproxy is fast transparent TCP/UDP/TLS (SSL) proxy. It's highly configurable
  and got many features.
  
  Core features:
     * intercept routed traffic, locally-originated traffic and SOCKS requests
     * Policy based traffic matching
     * Per-policy applicable profiles
     * Insightful CLI with configuration control
  
  Policy profiles:
     * content - replacing data online, writing to disk
     * dns - dns inspection settings
     * tls - per-policy specific settings
     * auth - match users and enforce authentication
     * detection - match specific patterns in the traffic
  
  TLS protocol:
     * dumping traffic plaintext into pcapng, text or remote GRE, exporting sslkeylog
     * TLS security checks (ocsp, ocsp stapling, automatic crl download)
     * Certificate Transparency checks for outbound connections
     * Html replacement warnings
     * STARTTLS support
     * Seamless redirection to login portal
  
  Other:
     * Simple authentication portal with local and ldap user support
     * SOCKS4/SOCKS5 support with DNS
     * DNS ALG
     * policies based on FQDN or 2nd level domain
     * both IPv4 and IPv6 is supported
  
  Complementary tools:
     * built-in tools to help with network redirections and certificates
     * check pplay tool (https://pypi.org/project/pplay/): replays captures
       over the network
  
  
   ... and many more!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core22

hooks:
  install:
    plugs: [ network, network-control ]

layout:
  /etc/smithproxy:
    bind: $SNAP_DATA/etc/smithproxy

  /etc/ca-certificates.conf:
    bind-file: $SNAP_DATA/etc/ca-certificates.conf

  /etc/wgetrc:
    bind-file: $SNAP_DATA/etc/wgetrc

  /usr/share/ca-certificates:
    bind: $SNAP_DATA/ca-bundle

  /etc/ssl/certs:
    bind: $SNAP_DATA/certs

  /etc/ca-certificates:
    bind: $SNAP_DATA/ca-certificates

  /usr/share/smithproxy:
    bind: $SNAP/usr/share/smithproxy

  /usr/bin/smithproxy:
    bind-file: $SNAP/usr/bin/smithproxy

  /usr/bin/smithd:
    bind-file: $SNAP/usr/bin/smithd

  /var/log/smithproxy:
    bind: $SNAP_DATA/log

  /var/smithproxy:
    bind: $SNAP_DATA/captures

  /usr/bin/telnet:
    bind-file: $SNAP/usr/bin/telnet.netkit

apps:
  svc-core:
    command: usr/bin/smithproxy --tenant-name default
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - network-control

  svc-net:
    command: usr/bin/sx_network start
    stop-command: usr/bin/sx_network stop
    daemon: oneshot
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control

  exe:
    command: usr/bin/smithproxy --tenant-name default
    plugs:
      - network
      - network-bind
      - network-control

  #  smithd:
  #    command: usr/bin/smithd
  #    plugs:
  #      - network
  #      - network-bind

  cli:
    command: usr/bin/sx_cli
    plugs:
      - network

  regencert:
    command: usr/bin/sx_regencerts
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
    plugs:
      - network   # to guess hostname and IP

  #  passwd:
  #    command: usr/bin/sx_passwd

  #  autoportalcert:
  #    command: usr/bin/sx_autoportalcert
  #    plugs:
  #      - network  # to guess hostname and IP

  certinfo-ca:
    command: usr/bin/sx_certinfo_ca

  download-ctlog:
    command: usr/bin/sx_download_ctlog
    plugs:
      - network

  download-ca-bundle:
    command: usr/bin/sx_download_ca_bundle
    plugs:
      - network


  net:
    command: usr/bin/sx_network
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control


parts:
  smithproxy:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release

    source: https://github.com/astibal/smithproxy
    source-type: git
    source-branch: release-0.9.31
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    #    source: .
    #    source-type: local

    build-packages:
      - g++
      - make
      - cmake
      - libconfig++-dev
      - python3-dev
      - libssl-dev
      - libffi-dev
      - libmicrohttpd-dev
      - libpam-dev
      - libxml2-dev
      - libxslt1-dev
      - libxmlsec1-dev
      - nlohmann-json3-dev

      - python3-distutils
      - telnet

    stage-packages:
      - ca-certificates
      - iptables
      - libconfig++9v5
      - libmicrohttpd12
      - telnet
      - wget
      - python3
      - python3-wheel
      - python3-posix-ipc
      - python3-distutils
      - python3-setuptools
      - python3-cryptography
      - swig

  pydeps:
    after: [ smithproxy ]
    plugin: python
    source: .
    source-type: local
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    override-build: |
      craftctl default
      pip3 install wheel
      pip3 install pylibconfig2

    build-packages:
      - python3-wheel

    python-packages:
      - wheel
      - pyparsing
