
name: smithproxy
version: 0.9.11-112-g677e2c8
summary: Fast and featured transparent TCP/UDP/TLS proxy
description: |
 Smithproxy is fast transparent TCP/UDP/TLS (SSL) proxy. It's highly configurable
 and got many features.

 Core features:
    * intercept routed traffic, locally-originated traffic and SOCKS requests
    * Policy based traffic matching
    * Per-policy applicable profiles
    * Insightful CLI with configuration control

 Policy profiles:
    * content - replacing data online, writing to disk
    * dns - dns inspection settigns
    * tls - per-policy specific settigns
    * auth - match users and enforce authentication
    * detection - match specific patterns in the traffic

 TLS protocol:
    * dumping plaintext to files, exporting sslkeylog
    * TLS security checks (ocsp, ocsp stapling, automatic crl download)
    * Certificate Transparency checks for outbound connections
    * Html replacement warnings
    * STARTTLS support
    * Seamless redirection to login portal

 Other:
    * Simple authentication portal with local and ldap user support
    * SOCKS4/SOCKS5 support with DNS
    * DNS ALG
    * policies based on FQDN or 2nd level domain
    * both IPv4 and IPv6 is supported

 Complementary tools:
    * built-in tools to help with network redirections and certificates
    * check pplay tool (https://pypi.org/project/pplay/): replays captures
      over the network


  ... and many more!

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

hooks:
  install:
    plugs: [ network, network-control ]

layout:
  /etc/smithproxy:
    bind: $SNAP_DATA/etc/smithproxy

  /etc/ca-certificates.conf:
    bind-file: $SNAP_DATA/etc/ca-certificates.conf

  /usr/share/ca-certificates:
    bind: $SNAP_DATA/ca-bundle

  /etc/ssl/certs:
    bind: $SNAP_DATA/certs

  /etc/ca-certificates:
    bind: $SNAP_DATA/ca-certificates

  /usr/share/smithproxy:
    bind: $SNAP/usr/share/smithproxy

  /usr/bin/smithproxy:
    bind-file: $SNAP/usr/bin/smithproxy

  /usr/bin/smithd:
    bind-file: $SNAP/usr/bin/smithd

  /var/log:
    bind: $SNAP_DATA/log

  /var/local/smithproxy:
    bind: $SNAP_DATA/captures

apps:
  exe:
    command: bin/smithproxy --tenant-index 0 --tenant-name default
    plugs:
      - network
      - network-bind
      - network-control

#  smithd:
#    command: bin/smithd
#    plugs:
#      - network
#      - network-bind

  cli:
    command: bin/sx_cli

  regencert:
    command: bin/sx_regencerts
    plugs:
      - network   # to guess hostname and IP

#  passwd:
#    command: bin/sx_passwd

#  autoportalcert:
#    command: bin/sx_autoportalcert
#    plugs:
#      - network  # to guess hostname and IP

  certinfo-ca:
    command: bin/sx_certinfo_ca

  download-ctlog:
    command: bin/sx_download_ctlog
    plugs:
      - network

  net:
    command: bin/sx_network
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control


parts:
  smithproxy:
    plugin: cmake

    source: https://github.com/astibal/smithproxy
    source-type: git
    source-branch: master

#    source: .
#    source-type: local

    build-packages:
      - g++
      - make
      - cmake
      - libconfig++-dev
      - libunwind-dev
      - python3-dev
      - libssl-dev
      - libffi-dev
      - try:
        - libxml2-dev
        - libxslt1-dev
        - xmlsec1-dev

      - python3-distutils
      - telnet

    stage-packages:
      - ca-certificates
      - iptables
      - libconfig++9v5
      - libunwind8
      - telnet
      - python
      - python3-ldap
      - python3-pyparsing
      - python3-posix-ipc
      - python3-distutils
      - swig

  pydeps:
    after: [ smithproxy ]
    plugin: python
    python-version: python3

    build-packages:
      - libssl-dev
      - python3-dev
      - python3-distutils
      - python3-setuptools
      - python3-pip
      - swig
      - libxml2-dev
      - libxslt1-dev
      - libxmlsec1-dev

    python-packages:
      - pyroute2
      - pylibconfig2
      - lxml
      - m2crypto
      - spyne>=2.13.2a0
      - zeep
      - cryptography
