
name: smithproxy
version: '0.9.2'
summary: Fast and featured transparent TCP/UDP/TLS proxy
description: |
 Smithproxy is fast transparent TCP/UDP/TLS (SSL) proxy. It's highly configurable
 and featured.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

layout:
  /etc:
    bind: $SNAP_DATA/etc

  /usr/share/smithproxy:
    bind: $SNAP/usr/share/smithproxy

  /usr/bin/smithproxy:
    bind-file: $SNAP/usr/bin/smithproxy

  /usr/bin/smithd:
    bind-file: $SNAP/usr/bin/smithd

  /var/log:
    bind: $SNAP_DATA/log

  /var/local/smithproxy:
    bind: $SNAP_DATA/captures

apps:
  exe:
    command: bin/smithproxy --tenant-index 0 --tenant-name default
    plugs:
      - network
      - network-bind
      - network-control

  smithd:
    command: bin/smithd
    plugs:
      - network
      - network-bind

  cli:
    command: bin/sx_cli

  regencert:
    command: bin/sx_regencerts
    plugs:
      - network   # to guess hostname and IP

  passwd:
    command: bin/sx_passwd

  autoportalcert:
    command: bin/sx_autoportalcert
    plugs:
      - network  # to guess hostname and IP

  certinfo-ca:
    command: bin/sx_certinfo_ca

  ctl:
    command: bin/sx_ctl
    plugs:
      - network
      - network-bind
      - network-control

  net:
    command: bin/sx_network
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control


parts:
  smithproxy:
    plugin: cmake
    source-type: git
    source: https://github.com/astibal/smithproxy
    source-branch: master
    build-packages:
      - g++-8
      - make
      - cmake
      - libcli-dev
      - libconfig++-dev
      - libunwind-dev
      - python3-dev
      - libssl-dev
      - python3-distutils
      - telnet

    stage-packages:
      - iptables
      - libcli1.9
      - libconfig++9v5
      - libunwind8
      - telnet
      - python
      - python3-ldap
      - python3-pyparsing
      - python3-posix-ipc
      - python3-distutils
      - swig

  pydeps:
    after: [ smithproxy ]
    plugin: python
    python-version: python3

    build-packages:
      - libssl-dev
      - python3-dev
      - python3-distutils
      - swig

    python-packages:
      - pyroute2
      - pylibconfig2
      - m2crypto
      - spyne>=2.13.2a0
      - zeep
      - cryptography
