#! /bin/sh
# /etc/init.d/smithproxy
#

# Some things that run always
# touch /var/lock/smithproxy

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting smithproxy"
    /etc/smithproxy/smithproxy.startup.sh start
    ;;
  stop)
    echo "Stopping smithproxy"
    /etc/smithproxy/smithproxy.startup.sh stop
    ;;
  *)
    echo "Usage: /etc/init.d/smithproxy {start|stop}"
    exit 1
    ;;
esac

exit 0
