#!/usr/bin/env bash
set -euo pipefail

[[ $# == 5 ]] || {
    echo 'Usage: remote-scheduler.sh BUNDLE WORK_ROOT MANIFEST PARALLEL OUTPUT_DIR' >&2
    exit 2
}

BUNDLE=$1
WORK_ROOT=$2
MANIFEST=$3
PARALLEL=$4
OUTPUT_DIR=$5

[[ $BUNDLE == /* && $WORK_ROOT == /* && $MANIFEST == /* && $OUTPUT_DIR == /* ]] || {
    echo 'All scheduler paths must be absolute' >&2
    exit 2
}
[[ $PARALLEL =~ ^[1-9][0-9]*$ ]] || { echo 'PARALLEL must be positive' >&2; exit 2; }
[[ -x $BUNDLE/tests/patch-runner/test-patch.sh ]] || { echo 'Missing staged patch runner' >&2; exit 2; }
[[ -x $BUNDLE/build/smithproxy ]] || { echo 'Missing staged smithproxy binary' >&2; exit 2; }
[[ -f $BUNDLE/coordinator-config.sh ]] || { echo 'Missing coordinator config' >&2; exit 2; }
[[ -f $MANIFEST ]] || { echo "Missing manifest: $MANIFEST" >&2; exit 2; }

# This file is generated by test-patch.sh exclusively with printf %q values.
# shellcheck source=/dev/null
source "$BUNDLE/coordinator-config.sh"

mkdir -p "$OUTPUT_DIR" "$WORK_ROOT/sections"
mapfile -t JOBS < <(sed '/^[[:space:]]*$/d' "$MANIFEST")

run_section() {
    local line=$1 job section seeds child_rc
    local -a fuzz_env=()
    IFS=$'\t' read -r job section seeds <<< "$line"
    [[ $job =~ ^[A-Za-z0-9._-]+$ ]] || { echo "Invalid job: $job" >&2; return 2; }
    [[ $section =~ ^[A-Za-z0-9._-]+$ ]] || { echo "Invalid section: $section" >&2; return 2; }
    if [[ $section == fuzz.* ]]; then
        [[ -n $seeds && $seeds != - ]] || { echo "Missing fuzz seeds for $section" >&2; return 2; }
        fuzz_env=(--env "FUZZ_SEEDS=$seeds" --env "FUZZ_LEVEL=$PATCH_RUN_FUZZ_LEVEL" --env FUZZ_SCATTER=1)
    fi

    set +e
    env PATCH_TEST_ROOT_OVERRIDE="$BUNDLE" \
        PATCH_TEST_COMMIT_OVERRIDE="$PATCH_RUN_COMMIT" \
        PATCH_TEST_BRANCH_OVERRIDE="$PATCH_RUN_BRANCH" \
        PATCH_TEST_DIRTY_OVERRIDE="$PATCH_RUN_DIRTY" \
        CURL_HTTP3_PREFIX="$BUNDLE/curl-http3" \
        QUIC_PYTHON_PREFIX="$BUNDLE/quic-python" \
        "$BUNDLE/tests/patch-runner/test-patch.sh" sanity \
        --skip-build --build-dir "$BUNDLE/build" --shared-binary "$BUNDLE/build/smithproxy" \
        --quiet --worker --local --suite "$section" --dir "$WORK_ROOT/sections/$job" \
        "${PATCH_RUN_ENV_ARGS[@]}" "${fuzz_env[@]}" > "$OUTPUT_DIR/$job.log" 2>&1
    child_rc=$?
    set -e
    printf '%s\n' "$child_rc" > "$OUTPUT_DIR/$job.rc"
    echo "SECTION DONE: $job suite=$section rc=$child_rc"
    return 0
}

declare -A PID_JOB=()
next=0
active=0
while ((next < ${#JOBS[@]} || active > 0)); do
    while ((next < ${#JOBS[@]} && active < PARALLEL)); do
        line=${JOBS[$next]}
        job=${line%%$'\t'*}
        echo "SECTION START: $job"
        run_section "$line" &
        pid=$!
        PID_JOB[$pid]=$job
        ((next += 1, active += 1))
    done
    if ((active > 0)); then
        done_pid=
        wait -n -p done_pid || true
        if [[ -n $done_pid && -n ${PID_JOB[$done_pid]:-} ]]; then
            : $((active -= 1))
            unset 'PID_JOB[$done_pid]'
        fi
    fi
done

for line in "${JOBS[@]}"; do
    job=${line%%$'\t'*}
    [[ -f $OUTPUT_DIR/$job.rc ]] || {
        echo "Scheduler lost result for $job" >&2
        exit 1
    }
done

# One archive per batch keeps result retrieval to one SCP connection.  Labs
# themselves remain on the execution target for detailed investigation.
relative_output=${OUTPUT_DIR#"$WORK_ROOT"/}
mapfile -t RESULT_DIRS < <(find "$WORK_ROOT/sections" -mindepth 2 -maxdepth 2 -type d -name results -printf '%P\n' | sed 's#^#sections/#' | sort)
tar -C "$WORK_ROOT" -cf "$OUTPUT_DIR.tar" "$relative_output" "${RESULT_DIRS[@]}"
chmod 0644 "$OUTPUT_DIR.tar"
