#!/usr/bin/env sh
set -eu

BASE_URL="https://github.com/astibal/smithproxy/releases/download/ctlog-latest"

sx_ctlog update \
    --url "${BASE_URL}/log_list.json" \
    --signature-url "${BASE_URL}/log_list.sig" \
    --signer-key "/usr/share/smithproxy/ctlog/smithproxy-ctlog-signer.pem" \
    --cache-dir "/var/cache/smithproxy/ctlog" \
    --output "/etc/smithproxy/ct_log_list.cnf"

echo "Smithproxy must be restarted to reload CT logs."
